### ISSUE TITLE
Update @angular-devkit/schematics dependency

### ISSUE THREAD

**Issue by Airblader** [nitayneeman/schematics-utilities#2]
The version for @angular-devkit/schematics is currently fixed, which pulls in a version of @angular-devkit/core that is broken and doesn't compile due to a typing error. It would be good to update the dependency and republish.

**Comment by Airblader** [comment]
@nitayneeman Any reaction here? Or can we consider this project dead? It's currently broken out of the box and requires the use of resoktiikns to force changing the dependencies.

**Comment by nitayneeman** [comment]
@Airblader Thanks for this report!

I'm very sorry for the long wait, but I couldn't reach to handle that in the recent past.
As you suggested, I've updated the dependencies (including  `@angular-devkit/schematics`) and obviously published a new version (1.1.2).

Please let me know your issue is resolved.

**Comment by Airblader** [comment]
Thank you! Seems to be working fine for now.
