### ISSUE TITLE
Upgrade @schematics/update to update ini to 1.3.6

### ISSUE THREAD

**Issue by DanielRuf** [nitayneeman/schematics-utilities#39]
The current version of `@schematics/update` still uses init 1.3.5 but this contains a vulnerability.

See https://snyk.io/vuln/SNYK-JS-INI-1048974

**Comment by mraible** [comment]
I agree this is a good idea. In fact, this project has lots of dependabot PRs that need to be merged. Can I help in any way @nitayneeman?

**Comment by nitayneeman** [comment]
Totally agree.

@mraible do you have an idea in mind regarding `@schematics/update`? Something you would like to suggest/contribute?

**Comment by mraible** [comment]
I'm not sure about `@schematics/update`. Is that some sort of command you can run?

My suggestion would be to merge the dependabot PRs to upgrade libraries and fix vulnerabilities, then release another version of this library.

**Comment by nitayneeman** [comment]
The dependabot PRs will be merged.

Regarding upgrading @schematics/update - the vulnerable ini was indeed upgraded in v9 of this package, but the thing is that bumping to such version might lead to breaking changes for `schematic-utilities`, since it requires aligning the other `@schematics` packages with v9.

We could patch the differences specifically although the wish is to upgrade them to v10 eventually and publish in another major version (v3). This is a critical task that was planned yet hasn't been done.
